AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false

require:
  - rubocop-minitest
  - rubocop-rake

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Max: 35
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Max: 250

Metrics/MethodLength:
  Max: 25

Minitest/MultipleAssertions:
  Enabled: false

Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false
