#!/usr/bin/env ruby
# frozen_string_literal: true

unless File.exist?("config/environment.rb")
  warn "Expected to be ran from the root of a Rails project"
  exit 1
end

require File.expand_path("config/environment")
require "xcopier/cli"

Xcopier::CLI.start(ARGV)
